# Introduction {#sec:introduction}

Recreational catch estimation of Chinook salmon in British Columbia has historically relied upon a combination of creel surveys and logbook programs. Creel surveys involve overflights that estimate effort and dockside interviews of fishers. These data are supplemented by logbook programs where guides and lodges voluntarily report catch information. However, both methods potentially have substantial spatial and temporal gaps, because they target the most heavily fished areas and months. A mandatory Internet Recreational Effort and Catch (iREC) survey has been used since 2013 to resolve these gaps and contribute to recreational catch data.

iREC is an online recreational catch reporting system that randomly selects recreational licence holders to self-report all recreational fishing activity, including kept and released fish by adipose clip status, for a given month of the year. The reporting covers all months and marine areas in the Pacific Region. Licence holders also report if they did not fish, which is equally as important as reported catch. The estimates from iREC are calibrated against creel survey estimates and combined to fill in spatial and temporal gaps where there are no complete catch estimates provided by the creel program but fishing does occur. The iREC survey data have been incorporated into the recreational catch in most regions domestically since 2013 using a variety of methods over time, but this has not occurred in a systematic and standardized way across the Pacific Region. Furthermore, iREC only began in July 2012 (as a pilot), which can cause issues when interpreting time series of catch data that span before and after iREC inclusion. 

Recreational catch estimates are an important data set for estimating exploitation rates, as required by the bilateral Pacific Salmon Treaty (PST) between the US and Canada. The PST defines calendar year exploitation rates (CYER) for Individual Stock Based Management (ISBM) fisheries, which limit stock-specific catch relative to a 2009-2015 base period [@PacificTreaty2019]. These CYER time series have historically combined incongruous data sources (a mix of yearly catch estimates without iREC (2009-2012) and yearly iREC-incorporated estimates (2013-2015)) creating a bias when comparing recent years to the base period. We resolved these discrepancies by creating a common recreational catch estimation methodology throughout the time series. The intention of these data revisions is to standardize Chinook salmon catch data inputs to both domestic and bilateral PST assessment processes. A key component to meeting PST requirements is to provide estimates of fishery impacts on coded wire tag (CWT) indicator stocks. Accordingly, stratification and estimation methods for CWT recoveries were revised to better align with the more complete catch estimates.

In this report, we describe the methods we used to estimate and validate Chinook recreational catch and present results on: (1) revised Chinook catch estimates for years with creel or logbook, or both, and iREC (method used for future catch estimates), (2) revised Chinook catch estimates for years without iREC back to 2005 (2005 being the earliest year that returning fish would contribute to the 2009 CYER of ocean fisheries, and thus impact the 2009-2015 CYER base period), (3) revised Chinook CWT estimates to reflect catch estimates, and (4) the incorporation of revised catch, CWT, and non-retention estimates into annual Chinook Technical Committee (CTC) reporting processes. We highlight both domestic and international PST processes affected by these data revisions. We then discuss potential further improvements to the analytical methods for applying these revisions and to catch monitoring to facilitate them.
