# Results



## Sport Head Recoveries

```{r Loading packages, useful functions, echo=FALSE}
#load packages
library(dplyr)
library(readr)
library(ggplot2)
library(ROracle)

#utils
"%notin%" <- Negate("%in%")
sport_catch <- pacRecCatch::wrangle_rec_catch("pacRecCatch_db.yaml")
models_combined <- pacRecCatch::model_rec_catch(sport_catch)
head_df <-  pacRecCatch::get_head_totals()

lm_eqn <- function(df){
  m <- lm(head_total ~ catch_estimate_predicted + 0, df)
  
  eq <- substitute(italic(y) == a %.% italic(x)*","~~italic(r)^2~"="~r2*"," ~~italic(n)*"="~df_n,
                   list(a = format(unname(coef(m)[1]), digits = 3),
                        b = format(unname(coef(m)[2]), digits = 3),
                        r2 = format(summary(m)$r.squared, digits = 3),
                        df_n = nrow(df)))
  as.character(as.expression(eq));
}

models_combined <-
  models_combined |>
  mutate(finescale_fishery = if_else(grepl("NWCVI|SWCVI", finescale_fishery), 
                                     trimws(gsub(" ISBM|AABM", "", finescale_fishery)),
                                     finescale_fishery)) |>
  group_by(YEAR, status, finescale_fishery, season, mark_status, kept_status) |>
  summarize(catch_estimate_predicted = sum(catch_estimate_predicted, na.rm=TRUE),
            .groups = "drop")

head_df <-
  head_df |>
  mutate(region = if_else(grepl("NWCVI|SWCVI", region), 
                          trimws(gsub(" ISBM|AABM", "", region)),
                          region)) |>
  group_by(year, region) |>
  summarize(head_total = sum(head_total, na.rm=TRUE),
            .groups = "drop")

head_catch_df <-
  models_combined |>
  filter(status == "marked_Kept_total") |>
  full_join(head_df, c(YEAR="year", finescale_fishery = "region")) |>
  mutate(YEAR = as.integer(YEAR),
         submit_rate = head_total/catch_estimate_predicted) |>
  filter(catch_estimate_predicted > 50)

head_catch_model_df <-
  head_catch_df |>
  filter(catch_estimate_predicted > 0, 
         coalesce(head_total, 0) > 0,
         coalesce(catch_estimate_predicted,0) > 0)

```

```{r Head to Kept Mark Catch, echo=FALSE}

ggplot(data = head_catch_model_df, aes(x=catch_estimate_predicted,
                                       y=head_total)) +
  geom_point(size=2) +
  geom_smooth(method='lm', formula= y~x + 0) +
  geom_text(x = 500, y = 5000, label = lm_eqn(head_catch_model_df), parse = TRUE, hjust=0, vjust=0) +
  ggtitle("Chinook Head to Clipped Catch") +
  xlab("Chinook Kept Adclipped Catch") + 
  ylab("Chinook Head Recoveries")


```

```{r Pre iRec Head to Kept Mark Catch, echo=FALSE}

pre_irec_catch_model_df <- 
  head_catch_model_df |>
  filter(YEAR < 2013)

eq_y_pos <- max(pre_irec_catch_model_df$head_total, na.rm=0) * 0.9

ggplot(data = pre_irec_catch_model_df,
       aes(x=catch_estimate_predicted, y=head_total)) +
  geom_point(size=2) +
  geom_smooth(method='lm', formula= y~x + 0) +
  geom_text(x = 500, y = eq_y_pos, label = lm_eqn(pre_irec_catch_model_df), parse = TRUE, hjust=0, vjust=0) +
  ggtitle("Before iRec Chinook Head to Clipped Catch") +
  xlab("Chinook Kept Adclipped Catch") + 
  ylab("Chinook Head Recoveries")

```

```{r Post iRec Head to Kept Mark Catch, echo=FALSE}

post_irec_catch_model_df <- 
  head_catch_model_df |>
  filter(YEAR >= 2013)

eq_y_pos <- max(post_irec_catch_model_df$head_total, na.rm=0) * 0.9

ggplot(data = post_irec_catch_model_df,
       aes(x=catch_estimate_predicted, y=head_total)) +
  geom_point(size=2) +
  geom_smooth(method='lm', formula= y~x + 0) +
  geom_text(x = 500, y = eq_y_pos, label = lm_eqn(post_irec_catch_model_df), parse = TRUE, hjust=0, vjust=0) +
  ggtitle("iRec Chinook Head to Clipped Catch") +
  xlab("Chinook Kept Adclipped Catch") + 
  ylab("Chinook Head Recoveries")

```

```{r Fishery Rates, echo=FALSE}

ggplot(data = head_catch_model_df, aes(x=YEAR, y=submit_rate, color=finescale_fishery)) +
  geom_line(linewidth = 2)

```

```{r pre IRec Fishery Rates, echo=FALSE}

ggplot(data = pre_irec_catch_model_df, aes(x=YEAR, y=submit_rate, color=finescale_fishery)) +
  geom_line(linewidth = 2)

```

