---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
\clearpage

# Discussion
This report reflects an effort to incorporate the best available Canadian recreational catch data into the current domestic and bilateral Chinook salmon stock assessment processes. We describe methods to produce standardized post-season recreational Chinook catch estimates from 2005 to present by integrating the iREC survey with the creel and logbook programs. The revised recreational catch estimates are more spatially and temporally complete and are better aligned with an independent data set from the Salmon Head Recovery Program, than previous estimates. This report recognizes decades of improvements to catch estimation methods. Applying and building upon these standardized methods in future years will allow us to continue to maintain and improve catch estimates time series over time.

The revised estimates that integrate iREC are broadly higher for both kept and released catch than previously reported estimates that only considered creel and logbooks as data sources. The higher kept catch estimates in turn generally contributed to higher and more consistent CWT estimates across fisheries and through time. Similarly, the higher released catch estimates generally contributed to higher overall release rates. Released catch increased more in the revisions than kept catch. 

The increases to kept catch are primarily due to iREC being more spatially and temporally complete than creel and logbook data, as the calibration of iREC to filtered creel estimates in recent years is approaching 1:1 in a given month and area (e.g., kept bias correction factor was 0.99 on average from 2020-2024 compared to 1.24 from 2013-2019, see Table \@ref(tab:tbl-irec-bcf-update)). This means that the estimates from these independent methods are converging which provides confidence in the accuracy of both the iREC and creel estimation methods. It is important to note that while estimates from each method are converging, the iREC survey can not be employed independently of the creel survey as it relies on creel for calibration and ground-truthing. Both the iREC estimates and the quality control criteria described in the methods can be used to direct our creel survey effort in the future. 

The released catch follows the same pattern to kept catch (more areas and months counted for iREC translates to higher releases counted than creel), but released catch in general (for both creel and iREC surveys) is more uncertain than kept catch. This is likely due to fisher recall (it is easier to recall the fish that you took home than the fish you released). Consequently, creel and logbook programs have historically captured release information poorly, although the Selective Fisheries Evaluation Committee has recently requested that these programs collect more detailed release information to support the analysis of mark selective fisheries. This bias towards underestimating releases was documented in the Strait of Georgia creel survey [@Diewert2005], in West Coast Vancouver Island (WCVI) troll fishery [@VelezEspino2010], and in Idaho creel surveys [e.g., @McCormick2013] by independent observer programs. Unlike kept catch and the SHRP, there is no ongoing independent verification of the enumeration of released catch (although see @Rechinsky2025 for recent verification of the composition of released catch). However, release rates have been relatively stable through time, until the recent introduction of mark selective fishing and Chinook non-retention in some fisheries, where release rates have been higher since 2019. This stability in the time series provides reassurance of release estimate precision and fisher recall, as large inter-year variability (without accompanying regulatory changes) would indicate a high degree of uncertainty in estimation.

The wide variability among fisheries in the magnitude of differences between revised and previously reported catch estimates are primarily driven by differences in data quality. For example, of all fisheries, Haida Gwaii Sport had the highest submission rates and lowest percent change in kept catch between revised and previous estimates, both of which aligned closely with the independent SHRP data set. This indicates both accurate estimates by the Haida Gwaii creel survey and high participation in the SHRP. Central BC sport only uses logbooks to estimate catch. The logbooks are also not a complete accounting of all lodges and historically an expansion factor was not applied to increase estimated catch. Consequently, the revised iREC estimates were among the highest relative to previous estimates across all fisheries and were much better aligned with sport head recoveries compared to the previous logbook-based catch estimates. iREC has therefore been incorporated into the CWT estimates for this fishery since 2019. 

Strait of Georgia Sport is another fishery with considerable differences between previous and revised catch estimates. The quality of southern Strait of Georgia creel in particular has varied over time with the passing rate, based on quality criteria, going from `r fmt_stat(all_summary_2005_2020b$pct[all_summary_2005_2020b$criteria == "passed"& all_summary_2005_2020b$region== "SGS"])`% (from 2005-2020) to `r fmt_stat(all_summary_2021_2025b$pct[all_summary_2021_2025b$criteria == "passed" & all_summary_2021_2025b$region== "SGS"])`% in the last five years (2021-2025). While this program has improved over time, creel surveys are still hindered by the region's complex geography, which limits the effectiveness of aerial surveys, and the large number of access sites, which make intercepting an adequate proportion of fishers in dockside interviews a challenge. iREC is well positioned to support the creel catch estimates in this region and consequently has been incorporated in all reporting on this fishery since 2018 (updating data back to 2013). The revised estimates for this fishery for 2005 through 2012 better align with recent catch estimates and create a timeline with a less pronounced step change than previously reported. Further, combined creel and iREC estimates better align with SHRP data than those from creel alone in this region, particularly in the spring and fall. The improved relationship, however, predicts lower head submission rates, highlighting that efforts to increase submission rates in this region may reduce uncertainty in associated CWT estimates. 

Within any given fishery, the quality of data underlying the revised estimates can vary widely. Higher iREC sample rates of recreational licence holders provide higher precision catch estimates in recent years, while the lack of iREC prior to 2013 and lower sample rates early in the monitoring program lead to more uncertain estimates in earlier years. The primary reason to extend the time series back to 2005 was to provide consistent estimates for the CTC CYER base period (i.e. 2009 to 2015) which required tracking impacts to associated cohorts back to 2005. Future fishery assessment metrics should focus on more recent years (e.g. since the start of iREC) to improve precision and reduce potential bias when assessing recreational fisheries.

While the modelling necessarily introduced uncertainty into the estimates, the modelled catch estimates provide a more complete representation of the fisheries than previous estimates because iREC has a much wider spatio-temporal coverage than creel or logbooks alone. The modelled estimates are better aligned with the independent SHRP data than previous estimates and provide a common currency across the CYER base period and into the future which is necessary for CYER evaluation. The largest changes between revised and previously reported estimates occur in the modelled period rather than the observed iREC period, mostly because iREC has been variably incorporated since 2013, but has never before been incorporated into pre-iREC catch. 

The best performing catch estimate models were by far the South Coast summer models which generally had a strong correlation between creel summer estimates and combined creel and iREC summer estimates. In contrast, South Coast seasonal models and Northern BC and Central BC annual models had poorer fits and weaker relationships between annual iREC and annual creel or logbook estimates or summertime iREC and seasonal creel estimates. Indeed, top performing seasonal models for WCVI and Johnstone Strait did not even include summer creel estimates as a predictor. However, although the flat relationships for these seasonal fisheries explain minimal variation in the data, they at least provide an intercept that can be used as an offset for predicting off-season catch; likely preferable to the previous practice of assuming zero catch in the spring and fall in these regions.

In some cases, the catch estimate models fit better as non-linear relationships (e.g., with Gamma distributions). This is potentially related to the quality control filtering process of creel estimates. As effort increases in a given area and month, it likely also increases in adjoining areas and months, resulting in more area and months being included in the regional model fit. However, this may not be the case when access to fishers is less of a concern. For example, a logbook program may be able to access fishers at lower efforts and provide an estimate when a creel survey may be less likely to encounter and interview fishers. This is potentially the case in the Haida Gwaii region (NBC AABM), where much of the fishing effort is carried out through lodges that participate in logbook programs. In this case, the logbook catch may have a more linear relationship with iREC catch as the bias is more evenly distributed throughout the much shorter, focused summer fishing season. Non-linearity of relationships between traditional surveys and iREC may also result from the difference in scale among the surveys and higher variability when catch estimates are high. 

Based on our work to date, when considering how to enhance the overall quality of recreational catch estimates in future years, we recommend focusing efforts on improving how existing data are integrated into catch estimation methods and building upon creel and iREC catch monitoring programs, as discussed below.

## Potential Estimation Improvements

The complexity of recreational catch monitoring and the extensive spatial scale of the fishery warrant further exploration of how to better apply data Canada collects to estimate catch. During the development of methods described in this report, we identified several potential improvements that should be considered in future work, including: 

 * refining the quality review processes to improve iREC and creel data,
 * improving the iREC-creel calibration process,
 * reviewing CWT submission rate stratification and indirect catch estimation methods,
 * incorporating creel and iREC uncertainty into model fits,
 * explore approaches to estimating mark rates.
 
As described in the methods, we defined and applied standardized data quality reviews to both the creel and iREC programs. However, as the iREC program continues to be developed and refined, more nuanced data quality reviews that incorporate additional information (e.g., regulations and fisher narratives provided with survey responses) could be explored. 

We also identified the calibration process between creel and iREC as a potential area for improvement. Currently, the calibration is carried out annually for each species by their mark status and disposition (i.e., kept or released) for all areas and months. This is a "one size fits all" approach applied to a diverse range of fishing communities and regulatory regimes. The propensity for anglers to respond to the survey and their potential recall bias may vary based on angler experience, their number of trips, or the regulations that apply to the periods or areas they fish. The proportion of fishers that are guided versus unguided and the relative adoption of the avid angler program may also differ among areas and months throughout the Pacific Region, in turn influencing the relationship between creel and iREC from one area and month to the next. Improvements to the calibration process could make it more sensitive to spatio-temporal differences, thereby mitigating potential confounding effects and improving the overall quality of catch estimates.

Historically, the most consistent and extensive creel program has been run in Southern BC marine waters and, for this reason, it has been applied to iREC calibrations to all regions of BC. However, as previously noted, fisher communities in Central and Northern BC may have different response rates and recall biases compared to Southern BC fishers. Accordingly, the creel and iREC calibration may be improved by incorporating creel data from these regions. However, while existing creel programs outside of southern BC follow approximately the same methods, they are implemented slightly differently and may not pass each of the of quality control criteria defined in the methods (e.g., number of flights). These programs should be reviewed to determine how to effectively incorporate data from these programs into consistent Central and Northern BC iREC calibration. 

Historic catch model fits may also be improved by accounting for uncertainty in all component data sets. A key feature of the iREC calibration process is the use of the error-in-variables approach that incorporates error in both iREC and creel catch estimates. A similar approach could be applied to historic catch models, potentially improving their accuracy and reducing possible bias of model fits, resulting in more robust estimates of catch for earlier years in the time series.

In recreational fisheries, accurate mark rates are an important component to estimating sample rates of CWT fish. As only heads of marked fish are contributed to the program, the sample rate is estimated using the estimate of marked kept catch. As part of both the iREC and creel programs, mark rate data is collected for both kept and released catch. The method defined in this report typically selects the mark rate from one of the sources (i.e., creel or iREC). In future iterations of our estimation methods, we could explore leveraging the combined mark sample data (i.e., combined creel and iREC) to reduce the overall uncertainty in the marked kept catch estimate, especially in areas and times with lower fishing effort. 

## Potential Catch Monitoring Improvements

A key component to these integrated recreational catch estimation methods is the operation of creel programs. The fisher-dependent nature of the iREC catch reporting can potentially bias catch estimates if it is relied upon solely. As described above, variability in fisher behaviour and participation rates can potentially introduce bias and reduce the precision of iREC catch estimates. Going forward, creel programs should continue to be a key component of recreational catch monitoring to ensure the integrity of recreational catch estimates.

Through the application of creel data in the catch estimation methods described in this report, we identified a number of shortcomings that may be mitigated through shifting how the program prioritizes monitoring. We excluded some past creel data from our analyses because they were too sparse to meet minimum inclusion criteria (e.g., included too few interviews or inadequate weekday or weekend overflight coverage). Where operationally feasible, it would be more beneficial to focus creel sampling on a smaller set of areas and months where more data can be collected rather than covering a wider spatio-temporal extent at a much lower sampling rate. This would maximize the amount of data from the creel program, particularly in the southern portion of BC, that could be used to accurately calibrate iREC.

One key consideration for the iREC program is how effective fishers are at communicating their catch data through the iREC reporting website. Issues, such as misunderstanding the reporting requirements of the iREC survey, or recall bias ^[Systematic error in that occurs when study participants do not remember past events or experiences accurately or completely] as a result of the time lag between catch and reporting, may reduce the quality of iREC data. Currently, the primary way to address these issues is to manually review comments provided by individual fishers. This may help resolve uncertainty in data due to misinterpreting survey questions and other issues with data entry, but is time intensive and subjective. A potentially more effective approach may be to collect fisher identification information during creel interviews (e.g., iREC access keys) to cross-reference with iREC reports. The limited number of creel interviews relative to the spatio-temporal coverage of iREC responses mean this additional information is not likely to inform the calibration directly, however, such a cross-reference between creel interviews and iREC surveys may help identify potentially systemic issues in how fishers interact with the iREC website.

A particular concern with iREC responses is the potential for recall bias resulting from the time lag between when a fishing event occurs and when it is reported in an iREC survey, which may exceed 1.5 months if the fisher waits until the deadline to report fishing events for their assigned reporting month. Therefore, any reduction to this lag may improve the overall accuracy of responses. One approach is to encourage fishers to actively record all their effort, catch, releases, and other required information (e.g., species, mark status, and length) while on the water, or shortly thereafter. DFO freely provides a document template ^[https://www.pac.dfo-mpo.gc.ca/fm-gp/rec/docs/track_catch-saisie_prises-eng.pdf] that can be printed out and carried by fishers while fishing. There are instructions on the recreational license to record all retained Chinook immediately in a table provided on the licence or to an electronic copy held in a third-party mobile application linked to their National Recreational Licensing System (NRLS) account, or directly in their NRLS account. Ideally, iREC could be linked directly to (or incorporated with) NRLS accounts so that fishers could enter iREC records at the same time that they record retained catches, consolidating all reporting requirements in one location. Emails or texts could automatically be sent to licence holders upon purchase with clear instructions on both licence and iREC reporting requirements and how and where to record information, along with links to online resources.

In general, the effectiveness of iREC is contingent on fishers knowing their responsibility to report their catch when they purchase a recreational licence. One demographic group that can be particularly challenging in this regard is guided fishers. These licence holders may be less familiar with fishing regulations, reporting requirements, the area in which they fish, or the identification of species they encounter or release. One solution is for guides to facilitate their patrons' reporting. This could be accomplished through a range of actions, from a communication campaign targeting guides and the recreational fishing industry to require guide reporting on behalf of patrons. These approaches should be considered to facilitate the improve the quality of response data from the iREC program.

# Conclusion
 
The primary goal of this work has been to incorporate direct catch estimation into a systematic, standardized, and replicable approach to better represent the impacts of Canadian marine recreational fisheries on Chinook stocks. Prior to this work, multiple methods were inconsistently applied to incorporate catch data from different sources to the estimation process. Our updated methods standardize how the data are integrated into recreational CWT estimates and how inconsistencies between sampling and catch estimates are handled. These updates leverage direct measurements and systematic methods to better reflect the recreational fishery impacts on CWT indicator stocks from 2005 to present. The revised methods described in this report provide a framework for ongoing improvements to recreational catch monitoring data and inform the operation and refinement of catch monitoring programs into the future.
