---
title: |
  "Chinook Salmon Marine Recreational Catch Data Revisions"
french_title: "Révisions des données de capture récréative du saumon chinook"
year: 2026
report_number: nnn
report_DOI: ???
author: |
  Norah E.M. Brown^1^, 
  Nicholas Komick^1^,
  Lauren Gill^1^,
  Kristopher Hein^1^,
  Rob Houtman^1^, 
  Noel Swain^1^, 
  Laura Tessier^1^, 
  Heidi Van Vliet^1^, 
  Catarina Wor^1^, and
  Antonio Vélez-Espino ^1^
author_list: "Brown, N.E.M., Komick, N., Gill, L., Hein, K., Houtman, R., Swain, N., Tessier, L., Van Vliet, H., Wor, C., and Vélez-Espino, A."
region: Pacific Region
french_region: Région du Pacifique
isbn: ""
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190 Hammond Bay Road\
     Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  
phone: "(555) 555-5555"
author_footnote: "Email: norah.brown@dfo-mpo.gc.ca"
citation_french: "Brown, N.E.M., Komick, N., Gill, L., Hein, K., Houtman, R., Swain, N., Tessier, L., Van Vliet, H., Wor, C., and Vélez-Espino, A. 2026. Révisions des données de capture récréative du saumon chinook. Can. Tech. Rep. Fish. Aquat. Sci. nnn: vii + 99 p. https://doi.org/???"

abstract: >
  Recreational catch estimation of Chinook salmon in the Pacific Region has historically been accomplished using a combination of creel surveys and logbook programs. However, there are substantial spatial and temporal gaps in the creel and logbook data, which are restricted to the most heavily fished areas and months. A mandatory Internet Recreational Effort and Catch (iREC) survey has been implemented since July 2012 to resolve these gaps and contribute to recreational catch information. Data from this survey have been variably incorporated into the Chinook recreational catch since 2013 (excluding 2012 as a pilot year) in most regions domestically, but this incorporation has not occurred in a standardized way. Furthermore, because iREC data were not available prior to 2013, incorporating them into recreational catch estimates confounds comparisons between pre- and post-2013 catch required to assess stock-specific impacts from Individual Stock Based Management fisheries as prescribed by the Pacific Salmon Treaty. Here, we present (1) revised catch estimates for years with creel and iREC overlap, (2) revised catch estimates for years without iREC back to 2005, (3) revised coded wire tag estimates that incorporate these revised catch estimates, and (4) how these revised estimates are incorporated into annual Chinook Technical Commmittee processes. We describe modelling and validation approaches that we used to calculate these revised estimates and identify potential areas for future refinement. This report recognizes decades of improvements to catch estimation methods and applying and building upon these standardized methods in future years will allow us to continue to maintain and improve catch estimates time series.

french_abstract: |
  L’estimation des prises récréatives de saumon Chinook dans la région du Pacifique a toujours été réalisée à l’aide d’une combinaison de relevés de pêcheurs et de programmes de journaux de bord. Cependant, il existe d’importantes lacunes spatiales et temporelles dans les données des pêcheurs et des journaux de bord, qui ciblent les zones et les mois les plus exploités. Depuis juillet 2012, une programme de déclaration de l’effort et des prises de la pêche récréative sur Internet (iREC) a été mis en œuvre afin de combler ces lacunes et de contribuer à l’information sur les prises récréatives. Depuis 2013, ces données ont été intégrées de façon variable dans les prises récréatives de saumon Chinook dans la plupart des zones, mais cette intégration ne s’est pas faite de manière normalisée. De plus, l’iREC n’a pas été intégré dans les estimations des prises avant 2013, ce qui rend difficile la comparaison des prises d’avant 2013 avec celles d’après 2013 et une exigence pour certains aspects du Traité sur le saumon du Pacifique (PST) pour les pêches de gestion individuelle des stocks (ISBM). Nous vous présentons ici (1) estimations révisées des prises de 2013 à 2023, méthodes à utiliser pour les estimations futures des prises, (2) estimations révisées des prises de 2005 à 2012, (3) l'intégration des deux ensembles d’estimations révisées dans les rapports du Comité technique du saumon Chinook (CTC), (4) l'intégration des deux séries d’estimations révisées dans les intrants des processus annuels du CTC. Nous décrivons les approches de modélisation et de validation que nous avons utilisées pour calculer ces estimations révisées et identifier les domaines potentiels d'amélioration. Ce rapport reconnaît des décennies d'améliorations des méthodes d'estimation des prises et l'application et le développement de ces méthodes standardisées dans les années à venir nous permettra de continuer à maintenir et à améliorer les séries chronologiques des estimations des prises.

show_continued_text: true
output:
 csasdowntex::techreport_pdf:
   french: false
   # copy_sty is a toggle to copy the style file from the csasdown package every time you compile
   # the document. If false, any changes you have made to the style file in your project
   # will remain between compilations. If true, your changes will be lost when you compile
   copy_sty: true
   # line_nums is a toggle to show line numbers on the left side of the page. 
   line_nums: true
   # line_nums_mod represents showing every Nth line if line_nums is true
   line_nums_mod: 1
   # lot_lof is a toggle to show/not show the lists of tables and figures at the
   # beginning of the document
   lot_lof: false
   # draft_watermark is a toggle to show/not show a DRAFT watermark across every page
   draft_watermark: false
   # highlight is the theme to use for code output. Must be one of the list given by:
   # pandoc --list-highlight-styles
   # which are:
   # pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock
   # or the name of a custom *.latex file which is most easily made by copying one from 
   # the csasdown library 'themes' directory, this directory on your machine:
   # file.path(.libPaths(), "csasdown", "themes")
   # to your working directory (the one containing index.Rmd)
   # To change the foreground text color, change the RGB value in the line containing
   # 'DefineVerbatimEnvironment'
   # To change background color, change the RGB values in the line containing 'shadecolor'
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) csasdowntex::render())
site: bookdown::bookdown_site
link-citations: true
always_allow_html: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
 - \usepackage[table, xcdraw]{xcolor}
 - \usepackage{pdflscape}
 
execute:
  echo: false
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "ragg_png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "ragg_png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_pos <- "H"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = "centre",
  fig.pos = fig_pos
)

knitr::opts_chunk$set(dev = "ragg_png")


```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(DiagrammeR)
library(ggplot2)
library(readr)
library(tibble)
library(tidyr)
library(rosettafish)
library(csasdowntex)


library(ROracle)
library(pacRecCatch)

library(odbc)
library(tidyr)
library(lubridate)
library(stringr)
library(ggnewscale)
library(gt)
library(patchwork)
library(DHARMa)
library(sf)
library(gtsummary)


#library(lme4)
#library(bbmle)
#library(SuppDists)
#library(MuMIn)

#utils
"%notin%" <- Negate("%in%")

#uncomment this section to pull fresh... but can use stored data for troubleshooting
# sport_catch_area <-
#   wrangle_rec_catch("pacRecCatch_db.yaml", by="area", most_recent_data_year=2025)
# 
# sport_catch_finescale <-
#   wrangle_rec_catch("pacRecCatch_db.yaml", by="fishery", most_recent_data_year=2025)
# 
# sport_catch_models <- model_rec_catch(sport_catch_finescale, most_recent_data_year=2023)
# 
# sport_release_rates <- get_release_rates(sport_catch_models, sport_catch_area)
# 
# creel_month_PFMA <- pacRecCatch::filter_creel_catch("pacRecCatch_db.yaml")
# 
# save(
#   sport_catch_area,
#  sport_catch_finescale,
#  sport_catch_models,
#  sport_release_rates,
#  creel_month_PFMA,
#  file = "data/sport_data.RData"
# )


  load("data/sport_data.RData")

  load("data/summer_models.RData")
  load("data/seasonal_models.RData")
  load("data/north_isbm_models.RData")
  load("data/north_aabm_models.RData")

#   library(writexl)
#   write_xlsx(
#   list(
#     "By_area_2013to2023" = sport_catch_area,
#     "By_finescale_2005to2025" = sport_catch_models$model_catch
#   ),
#   "data/revised_chinook_catch.xlsx"
# )
  
```
